language: node_js
node_js: "12.13.0"

install:
  - cd test
  - npm ci


matrix:
  include:
  - name: "Linux Test"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX Test"
    os: osx
  - name: "Windows Test"
    os: windows
    before_install:
      # Fix travis bug "git-sh-setup: file not found"
      - export PATH=$PATH:"/c/Program Files/Git/mingw64/libexec/git-core"
