language: node_js
node_js: "12.13.0"

install:
  - cd test
  - npm ci


matrix:
  include:
  - name: "Linux Test"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX Test"
    os: osx
  - name: "Windows Test"
    os: windows
